### PR TITLE
increase vllm pod startup to 30 min

### LINKED ISSUE #172: timeout is too short on health check for vllm
The current timeout seems to be 900 seconds. We should have a startup probe instead that is up to 30 minutes. Since large models can take a long time.

As a follow up we may want to consider making a startup timeout configurable with a default of 30 minutes.

current pod config for vllm:
```
					ReadinessProbe: &corev1.Probe{
						FailureThreshold:    3,
						InitialDelaySeconds: 20,
						PeriodSeconds:       10,
						TimeoutSeconds:      2,
						SuccessThreshold:    1,
						ProbeHandler: corev1.ProbeHandler{
							HTTPGet: &corev1.HTTPGetAction{
								Path: "/health",
								Port: intstr.FromString("http"),
							},
						},
					},
					LivenessProbe: &corev1.Probe{
						FailureThreshold:    3,
						InitialDelaySeconds: 900,
						PeriodSeconds:       30,
						TimeoutSeconds:      3,
						SuccessThreshold:    1,
						ProbeHandler: corev1.ProbeHandler{
							HTTPGet: &corev1.HTTPGetAction{
								Path: "/health",
								Port: intstr.FromString("http"),
							},
						},
					},
```

### PR DESCRIPTION
**Pull request by samos123**
fixes #172

### CODE REVIEW

**Comment by nstogner** [comment]
LGTM, one optimization: I see no reason to not shorten the period for the startup probe to 1-2sec

**Comment by mike-ensor** [comment]
Any chance this could be a configurable component?  Networks will all differ when using this on any system outside of a major cloud.  Llama3.1 8B is 4.6GB (https://ollama.com/library/llama3.1:8b) of storage. 20Mbps (which used to be the standard for FCC "Broadband") would be 30min of download if you have the whole bandwidth to work with ([Calculator](https://www.omnicalculator.com/other/bandwidth?calculatorResult=H4sIAAAAAAAAA51VTW%2FbMAz9K4WwQ1JkWRKsaBGgBbYGA3Joe8jaS9GDYjOONkk29BEsK%2FzfR8pxLK%2BpkdQnidQj%2BahH%2BZWBzoSGheMO2PSVJVwmXuImfeJG8KUEe88VWDZ9Zk4oYC8Dlqy5zg4dsAVAygbNwVynwolcWwotdOFda2HFXxiOaLXh0mP%2BYDm7uT4bYZQUHCRxISEFHmAv5aDKNRy3wGTqRocCCU4lDicxmiyd4IpVieDcuzcMOqod1Dmc8YCpjcgyMEJn9VlqIJtqL2WbWBeH04I2dDuonRKS2uBFfJtxX4Ibb38DxuL1%2F8iNQlHZumNBaHvvvPbjJfTGo%2Fo77xlYgQGdwBOV1e%2BzOOaDdzHsSwPsn%2FfeQuvGdqWeXHwgbQC9lzL09f2Mp6Q6EB8TAJ69PWJk4Y8zfMYdDzdmv6UbjpGwGysuLd61sHf5UkjYG7wFU1XutTPb2zylGXlcUIXeUB3bsJ9FhsVWLXOJ5k9olPhGeJ7BDgn6cwBj3LkqUFVcPmrhbCU2orKquJJ1BgXolELe8aKSlsyT3wcIIjXFtedyTir8T2AKTXSadoq79S%2F0s%2B8iu%2Fdqiez2cmdfh5dsp%2Bd6HYnl6DCT0T4KLcu6tgMPJdU4aEa5GpwHLbfxWNYD2aJVFXlZiz0o5niiDa6MSVY1X3wgYg0qW2o%2FGj6%2BumqaVm0okoEkF3L%2FU%2BLe5ZZvoPX8JbmUvLCQztNds9Ygi5%2Bo9FgxlceCDI9ekNxC%2BqzV0sIIxQ3pORMZX24xadycxq0A3cLFk90418YqoS0kRKH8B4cE5%2FxZBwAA))

**Comment by samos123** [comment]
I have filed a separate issue for making it configurable: https://github.com/substratusai/kubeai/issues/176

**Comment by samos123** [comment]
I also changed startup probe period to 2 seconds while keeping timeout at 30 minutes. @nstogner please review again.

**Pull request merged**
